# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_setting_specifics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import extension_setting_specifics_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='app_setting_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x1b\x61pp_setting_specifics.proto\x12\x07sync_pb\x1a!extension_setting_specifics.proto\"T\n\x13\x41ppSettingSpecifics\x12=\n\x11\x65xtension_setting\x18\x01 \x01(\x0b\x32\".sync_pb.ExtensionSettingSpecificsB\x04H\x03`\x01')




_APPSETTINGSPECIFICS = _descriptor.Descriptor(
  name='AppSettingSpecifics',
  full_name='sync_pb.AppSettingSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extension_setting', full_name='sync_pb.AppSettingSpecifics.extension_setting', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=75,
  serialized_end=159,
)

_APPSETTINGSPECIFICS.fields_by_name['extension_setting'].message_type = extension_setting_specifics_pb2._EXTENSIONSETTINGSPECIFICS
DESCRIPTOR.message_types_by_name['AppSettingSpecifics'] = _APPSETTINGSPECIFICS

class AppSettingSpecifics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _APPSETTINGSPECIFICS

  # @@protoc_insertion_point(class_scope:sync_pb.AppSettingSpecifics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
# @@protoc_insertion_point(module_scope)
