# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attachments.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='attachments.proto',
  package='sync_pb',
  serialized_pb='\n\x11\x61ttachments.proto\x12\x07sync_pb\"&\n\x11\x41ttachmentIdProto\x12\x11\n\tunique_id\x18\x01 \x01(\t\"X\n\x18\x41ttachmentMetadataRecord\x12&\n\x02id\x18\x01 \x01(\x0b\x32\x1a.sync_pb.AttachmentIdProto\x12\x14\n\x0cis_on_server\x18\x02 \x01(\x08\"G\n\x12\x41ttachmentMetadata\x12\x31\n\x06record\x18\x01 \x03(\x0b\x32!.sync_pb.AttachmentMetadataRecordB\x04H\x03`\x01')




_ATTACHMENTIDPROTO = _descriptor.Descriptor(
  name='AttachmentIdProto',
  full_name='sync_pb.AttachmentIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unique_id', full_name='sync_pb.AttachmentIdProto.unique_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=68,
)


_ATTACHMENTMETADATARECORD = _descriptor.Descriptor(
  name='AttachmentMetadataRecord',
  full_name='sync_pb.AttachmentMetadataRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sync_pb.AttachmentMetadataRecord.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_on_server', full_name='sync_pb.AttachmentMetadataRecord.is_on_server', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=70,
  serialized_end=158,
)


_ATTACHMENTMETADATA = _descriptor.Descriptor(
  name='AttachmentMetadata',
  full_name='sync_pb.AttachmentMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record', full_name='sync_pb.AttachmentMetadata.record', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=160,
  serialized_end=231,
)

_ATTACHMENTMETADATARECORD.fields_by_name['id'].message_type = _ATTACHMENTIDPROTO
_ATTACHMENTMETADATA.fields_by_name['record'].message_type = _ATTACHMENTMETADATARECORD
DESCRIPTOR.message_types_by_name['AttachmentIdProto'] = _ATTACHMENTIDPROTO
DESCRIPTOR.message_types_by_name['AttachmentMetadataRecord'] = _ATTACHMENTMETADATARECORD
DESCRIPTOR.message_types_by_name['AttachmentMetadata'] = _ATTACHMENTMETADATA

class AttachmentIdProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ATTACHMENTIDPROTO

  # @@protoc_insertion_point(class_scope:sync_pb.AttachmentIdProto)

class AttachmentMetadataRecord(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ATTACHMENTMETADATARECORD

  # @@protoc_insertion_point(class_scope:sync_pb.AttachmentMetadataRecord)

class AttachmentMetadata(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ATTACHMENTMETADATA

  # @@protoc_insertion_point(class_scope:sync_pb.AttachmentMetadata)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
# @@protoc_insertion_point(module_scope)
