# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autofill_specifics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='autofill_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x18\x61utofill_specifics.proto\x12\x07sync_pb\"\xb5\x04\n\x18\x41utofillProfileSpecifics\x12\x0c\n\x04guid\x18\x0f \x01(\t\x12\x0e\n\x06origin\x18\x10 \x01(\t\x12\x12\n\nname_first\x18\x02 \x03(\t\x12\x13\n\x0bname_middle\x18\x03 \x03(\t\x12\x11\n\tname_last\x18\x04 \x03(\t\x12\x15\n\remail_address\x18\x05 \x03(\t\x12\x14\n\x0c\x63ompany_name\x18\x06 \x01(\t\x12\x1a\n\x12\x61\x64\x64ress_home_line1\x18\x07 \x01(\t\x12\x1a\n\x12\x61\x64\x64ress_home_line2\x18\x08 \x01(\t\x12\x19\n\x11\x61\x64\x64ress_home_city\x18\t \x01(\t\x12\x1a\n\x12\x61\x64\x64ress_home_state\x18\n \x01(\t\x12\x18\n\x10\x61\x64\x64ress_home_zip\x18\x0b \x01(\t\x12\x1c\n\x14\x61\x64\x64ress_home_country\x18\x0c \x01(\t\x12#\n\x1b\x61\x64\x64ress_home_street_address\x18\x11 \x01(\t\x12!\n\x19\x61\x64\x64ress_home_sorting_code\x18\x12 \x01(\t\x12\'\n\x1f\x61\x64\x64ress_home_dependent_locality\x18\x13 \x01(\t\x12\"\n\x1a\x61\x64\x64ress_home_language_code\x18\x14 \x01(\t\x12\x1f\n\x17phone_home_whole_number\x18\r \x03(\t\x12\x11\n\x05label\x18\x01 \x01(\tB\x02\x18\x01\x12\"\n\x16phone_fax_whole_number\x18\x0e \x01(\tB\x02\x18\x01\"}\n\x11\x41utofillSpecifics\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x17\n\x0fusage_timestamp\x18\x03 \x03(\x03\x12\x32\n\x07profile\x18\x04 \x01(\x0b\x32!.sync_pb.AutofillProfileSpecificsB\x04H\x03`\x01')




_AUTOFILLPROFILESPECIFICS = _descriptor.Descriptor(
  name='AutofillProfileSpecifics',
  full_name='sync_pb.AutofillProfileSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='sync_pb.AutofillProfileSpecifics.guid', index=0,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin', full_name='sync_pb.AutofillProfileSpecifics.origin', index=1,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name_first', full_name='sync_pb.AutofillProfileSpecifics.name_first', index=2,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name_middle', full_name='sync_pb.AutofillProfileSpecifics.name_middle', index=3,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name_last', full_name='sync_pb.AutofillProfileSpecifics.name_last', index=4,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email_address', full_name='sync_pb.AutofillProfileSpecifics.email_address', index=5,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='company_name', full_name='sync_pb.AutofillProfileSpecifics.company_name', index=6,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_home_line1', full_name='sync_pb.AutofillProfileSpecifics.address_home_line1', index=7,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_home_line2', full_name='sync_pb.AutofillProfileSpecifics.address_home_line2', index=8,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_home_city', full_name='sync_pb.AutofillProfileSpecifics.address_home_city', index=9,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_home_state', full_name='sync_pb.AutofillProfileSpecifics.address_home_state', index=10,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_home_zip', full_name='sync_pb.AutofillProfileSpecifics.address_home_zip', index=11,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_home_country', full_name='sync_pb.AutofillProfileSpecifics.address_home_country', index=12,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_home_street_address', full_name='sync_pb.AutofillProfileSpecifics.address_home_street_address', index=13,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_home_sorting_code', full_name='sync_pb.AutofillProfileSpecifics.address_home_sorting_code', index=14,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_home_dependent_locality', full_name='sync_pb.AutofillProfileSpecifics.address_home_dependent_locality', index=15,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address_home_language_code', full_name='sync_pb.AutofillProfileSpecifics.address_home_language_code', index=16,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone_home_whole_number', full_name='sync_pb.AutofillProfileSpecifics.phone_home_whole_number', index=17,
      number=13, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='sync_pb.AutofillProfileSpecifics.label', index=18,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')),
    _descriptor.FieldDescriptor(
      name='phone_fax_whole_number', full_name='sync_pb.AutofillProfileSpecifics.phone_fax_whole_number', index=19,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=603,
)


_AUTOFILLSPECIFICS = _descriptor.Descriptor(
  name='AutofillSpecifics',
  full_name='sync_pb.AutofillSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='sync_pb.AutofillSpecifics.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='sync_pb.AutofillSpecifics.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='usage_timestamp', full_name='sync_pb.AutofillSpecifics.usage_timestamp', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='profile', full_name='sync_pb.AutofillSpecifics.profile', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=605,
  serialized_end=730,
)

_AUTOFILLSPECIFICS.fields_by_name['profile'].message_type = _AUTOFILLPROFILESPECIFICS
DESCRIPTOR.message_types_by_name['AutofillProfileSpecifics'] = _AUTOFILLPROFILESPECIFICS
DESCRIPTOR.message_types_by_name['AutofillSpecifics'] = _AUTOFILLSPECIFICS

class AutofillProfileSpecifics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTOFILLPROFILESPECIFICS

  # @@protoc_insertion_point(class_scope:sync_pb.AutofillProfileSpecifics)

class AutofillSpecifics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTOFILLSPECIFICS

  # @@protoc_insertion_point(class_scope:sync_pb.AutofillSpecifics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
_AUTOFILLPROFILESPECIFICS.fields_by_name['label'].has_options = True
_AUTOFILLPROFILESPECIFICS.fields_by_name['label']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')
_AUTOFILLPROFILESPECIFICS.fields_by_name['phone_fax_whole_number'].has_options = True
_AUTOFILLPROFILESPECIFICS.fields_by_name['phone_fax_whole_number']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')
# @@protoc_insertion_point(module_scope)
