# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_commands.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_commands.proto',
  package='sync_pb',
  serialized_pb='\n\x15\x63lient_commands.proto\x12\x07sync_pb\"\x88\x02\n\rClientCommand\x12\x1e\n\x16set_sync_poll_interval\x18\x01 \x01(\x05\x12#\n\x1bset_sync_long_poll_interval\x18\x02 \x01(\x05\x12\x1d\n\x15max_commit_batch_size\x18\x03 \x01(\x05\x12%\n\x1dsessions_commit_delay_seconds\x18\x04 \x01(\x05\x12\x1e\n\x16throttle_delay_seconds\x18\x05 \x01(\x05\x12,\n$client_invalidation_hint_buffer_size\x18\x06 \x01(\x05\x12\x1e\n\x16gu_retry_delay_seconds\x18\x07 \x01(\x05\x42\x04H\x03`\x01')




_CLIENTCOMMAND = _descriptor.Descriptor(
  name='ClientCommand',
  full_name='sync_pb.ClientCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='set_sync_poll_interval', full_name='sync_pb.ClientCommand.set_sync_poll_interval', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set_sync_long_poll_interval', full_name='sync_pb.ClientCommand.set_sync_long_poll_interval', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_commit_batch_size', full_name='sync_pb.ClientCommand.max_commit_batch_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sessions_commit_delay_seconds', full_name='sync_pb.ClientCommand.sessions_commit_delay_seconds', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='throttle_delay_seconds', full_name='sync_pb.ClientCommand.throttle_delay_seconds', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_invalidation_hint_buffer_size', full_name='sync_pb.ClientCommand.client_invalidation_hint_buffer_size', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gu_retry_delay_seconds', full_name='sync_pb.ClientCommand.gu_retry_delay_seconds', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=299,
)

DESCRIPTOR.message_types_by_name['ClientCommand'] = _CLIENTCOMMAND

class ClientCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTCOMMAND

  # @@protoc_insertion_point(class_scope:sync_pb.ClientCommand)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
# @@protoc_insertion_point(module_scope)
