# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dictionary_specifics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dictionary_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x1a\x64ictionary_specifics.proto\x12\x07sync_pb\"#\n\x13\x44ictionarySpecifics\x12\x0c\n\x04word\x18\x01 \x01(\tB\x04H\x03`\x01')




_DICTIONARYSPECIFICS = _descriptor.Descriptor(
  name='DictionarySpecifics',
  full_name='sync_pb.DictionarySpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='sync_pb.DictionarySpecifics.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['DictionarySpecifics'] = _DICTIONARYSPECIFICS

class DictionarySpecifics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DICTIONARYSPECIFICS

  # @@protoc_insertion_point(class_scope:sync_pb.DictionarySpecifics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
# @@protoc_insertion_point(module_scope)
