# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: managed_user_specifics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='managed_user_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x1cmanaged_user_specifics.proto\x12\x07sync_pb\"\xd2\x01\n\x14ManagedUserSpecifics\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1b\n\x0c\x61\x63knowledged\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x12\n\nmaster_key\x18\x04 \x01(\t\x12\x15\n\rchrome_avatar\x18\x05 \x01(\t\x12\x17\n\x0f\x63hromeos_avatar\x18\x06 \x01(\t\x12\x1e\n\x16password_signature_key\x18\x07 \x01(\t\x12\x1f\n\x17password_encryption_key\x18\x08 \x01(\tB\x04H\x03`\x01')




_MANAGEDUSERSPECIFICS = _descriptor.Descriptor(
  name='ManagedUserSpecifics',
  full_name='sync_pb.ManagedUserSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sync_pb.ManagedUserSpecifics.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='sync_pb.ManagedUserSpecifics.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acknowledged', full_name='sync_pb.ManagedUserSpecifics.acknowledged', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='master_key', full_name='sync_pb.ManagedUserSpecifics.master_key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chrome_avatar', full_name='sync_pb.ManagedUserSpecifics.chrome_avatar', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chromeos_avatar', full_name='sync_pb.ManagedUserSpecifics.chromeos_avatar', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password_signature_key', full_name='sync_pb.ManagedUserSpecifics.password_signature_key', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password_encryption_key', full_name='sync_pb.ManagedUserSpecifics.password_encryption_key', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=252,
)

DESCRIPTOR.message_types_by_name['ManagedUserSpecifics'] = _MANAGEDUSERSPECIFICS

class ManagedUserSpecifics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MANAGEDUSERSPECIFICS

  # @@protoc_insertion_point(class_scope:sync_pb.ManagedUserSpecifics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
# @@protoc_insertion_point(module_scope)
