# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: password_specifics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import encryption_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='password_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x18password_specifics.proto\x12\x07sync_pb\x1a\x10\x65ncryption.proto\"\xb4\x02\n\x15PasswordSpecificsData\x12\x0e\n\x06scheme\x18\x01 \x01(\x05\x12\x14\n\x0csignon_realm\x18\x02 \x01(\t\x12\x0e\n\x06origin\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x18\n\x10username_element\x18\x05 \x01(\t\x12\x16\n\x0eusername_value\x18\x06 \x01(\t\x12\x18\n\x10password_element\x18\x07 \x01(\t\x12\x16\n\x0epassword_value\x18\x08 \x01(\t\x12\x11\n\tssl_valid\x18\t \x01(\x08\x12\x11\n\tpreferred\x18\n \x01(\x08\x12\x14\n\x0c\x64\x61te_created\x18\x0b \x01(\x03\x12\x13\n\x0b\x62lacklisted\x18\x0c \x01(\x08\x12\x0c\n\x04type\x18\r \x01(\x05\x12\x12\n\ntimes_used\x18\x0e \x01(\x05\"\x82\x01\n\x11PasswordSpecifics\x12)\n\tencrypted\x18\x01 \x01(\x0b\x32\x16.sync_pb.EncryptedData\x12\x42\n\x1a\x63lient_only_encrypted_data\x18\x02 \x01(\x0b\x32\x1e.sync_pb.PasswordSpecificsDataB\x04H\x03`\x01')




_PASSWORDSPECIFICSDATA = _descriptor.Descriptor(
  name='PasswordSpecificsData',
  full_name='sync_pb.PasswordSpecificsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scheme', full_name='sync_pb.PasswordSpecificsData.scheme', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signon_realm', full_name='sync_pb.PasswordSpecificsData.signon_realm', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin', full_name='sync_pb.PasswordSpecificsData.origin', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='sync_pb.PasswordSpecificsData.action', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username_element', full_name='sync_pb.PasswordSpecificsData.username_element', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username_value', full_name='sync_pb.PasswordSpecificsData.username_value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password_element', full_name='sync_pb.PasswordSpecificsData.password_element', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password_value', full_name='sync_pb.PasswordSpecificsData.password_value', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ssl_valid', full_name='sync_pb.PasswordSpecificsData.ssl_valid', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preferred', full_name='sync_pb.PasswordSpecificsData.preferred', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date_created', full_name='sync_pb.PasswordSpecificsData.date_created', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blacklisted', full_name='sync_pb.PasswordSpecificsData.blacklisted', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='sync_pb.PasswordSpecificsData.type', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='times_used', full_name='sync_pb.PasswordSpecificsData.times_used', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=56,
  serialized_end=364,
)


_PASSWORDSPECIFICS = _descriptor.Descriptor(
  name='PasswordSpecifics',
  full_name='sync_pb.PasswordSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypted', full_name='sync_pb.PasswordSpecifics.encrypted', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_only_encrypted_data', full_name='sync_pb.PasswordSpecifics.client_only_encrypted_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=367,
  serialized_end=497,
)

_PASSWORDSPECIFICS.fields_by_name['encrypted'].message_type = encryption_pb2._ENCRYPTEDDATA
_PASSWORDSPECIFICS.fields_by_name['client_only_encrypted_data'].message_type = _PASSWORDSPECIFICSDATA
DESCRIPTOR.message_types_by_name['PasswordSpecificsData'] = _PASSWORDSPECIFICSDATA
DESCRIPTOR.message_types_by_name['PasswordSpecifics'] = _PASSWORDSPECIFICS

class PasswordSpecificsData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PASSWORDSPECIFICSDATA

  # @@protoc_insertion_point(class_scope:sync_pb.PasswordSpecificsData)

class PasswordSpecifics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PASSWORDSPECIFICS

  # @@protoc_insertion_point(class_scope:sync_pb.PasswordSpecifics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
# @@protoc_insertion_point(module_scope)
