# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: priority_preference_specifics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import preference_specifics_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='priority_preference_specifics.proto',
  package='sync_pb',
  serialized_pb='\n#priority_preference_specifics.proto\x12\x07sync_pb\x1a\x1apreference_specifics.proto\"O\n\x1bPriorityPreferenceSpecifics\x12\x30\n\npreference\x18\x01 \x01(\x0b\x32\x1c.sync_pb.PreferenceSpecificsB\x04H\x03`\x01')




_PRIORITYPREFERENCESPECIFICS = _descriptor.Descriptor(
  name='PriorityPreferenceSpecifics',
  full_name='sync_pb.PriorityPreferenceSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preference', full_name='sync_pb.PriorityPreferenceSpecifics.preference', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=155,
)

_PRIORITYPREFERENCESPECIFICS.fields_by_name['preference'].message_type = preference_specifics_pb2._PREFERENCESPECIFICS
DESCRIPTOR.message_types_by_name['PriorityPreferenceSpecifics'] = _PRIORITYPREFERENCESPECIFICS

class PriorityPreferenceSpecifics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PRIORITYPREFERENCESPECIFICS

  # @@protoc_insertion_point(class_scope:sync_pb.PriorityPreferenceSpecifics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
# @@protoc_insertion_point(module_scope)
