# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synced_notification_app_info_specifics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import synced_notification_render_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='synced_notification_app_info_specifics.proto',
  package='sync_pb',
  serialized_pb='\n,synced_notification_app_info_specifics.proto\x12\x07sync_pb\x1a synced_notification_render.proto\"n\n\"SyncedNotificationAppInfoSpecifics\x12H\n\x1csynced_notification_app_info\x18\x01 \x03(\x0b\x32\".sync_pb.SyncedNotificationAppInfo\"\xde\x03\n\x19SyncedNotificationAppInfo\x12\x0e\n\x06\x61pp_id\x18\x01 \x03(\t\x12!\n\x15settings_display_name\x18\x02 \x01(\tB\x02\x18\x01\x12\x32\n\x04icon\x18\x03 \x01(\x0b\x32 .sync_pb.SyncedNotificationImageB\x02\x18\x01\x12\x10\n\x08\x61pp_name\x18\x04 \x01(\t\x12\x14\n\x0csettings_url\x18\x05 \x01(\t\x12\x10\n\x08info_url\x18\x06 \x01(\t\x12\x39\n\x08\x61pp_icon\x18\x07 \x03(\x0b\x32\'.sync_pb.SyncedNotificationAppInfo.Icon\x1a\xe4\x01\n\x04Icon\x12:\n\x04type\x18\x01 \x01(\x0e\x32,.sync_pb.SyncedNotificationAppInfo.Icon.Type\x12\x0b\n\x03url\x18\x02 \x01(\t\"\x92\x01\n\x04Type\x12\x18\n\x14GRAYSCALE_FAVICON_1X\x10\x01\x12\x18\n\x14GRAYSCALE_FAVICON_2X\x10\x02\x12\x14\n\x10\x43OLOR_FAVICON_1X\x10\x03\x12\x14\n\x10\x43OLOR_FAVICON_2X\x10\x04\x12\x14\n\x10\x43OLOR_APPICON_1X\x10\x05\x12\x14\n\x10\x43OLOR_APPICON_2X\x10\x06\x42\x04H\x03`\x01')



_SYNCEDNOTIFICATIONAPPINFO_ICON_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='sync_pb.SyncedNotificationAppInfo.Icon.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GRAYSCALE_FAVICON_1X', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GRAYSCALE_FAVICON_2X', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLOR_FAVICON_1X', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLOR_FAVICON_2X', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLOR_APPICON_1X', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLOR_APPICON_2X', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=536,
  serialized_end=682,
)


_SYNCEDNOTIFICATIONAPPINFOSPECIFICS = _descriptor.Descriptor(
  name='SyncedNotificationAppInfoSpecifics',
  full_name='sync_pb.SyncedNotificationAppInfoSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='synced_notification_app_info', full_name='sync_pb.SyncedNotificationAppInfoSpecifics.synced_notification_app_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=91,
  serialized_end=201,
)


_SYNCEDNOTIFICATIONAPPINFO_ICON = _descriptor.Descriptor(
  name='Icon',
  full_name='sync_pb.SyncedNotificationAppInfo.Icon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='sync_pb.SyncedNotificationAppInfo.Icon.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='sync_pb.SyncedNotificationAppInfo.Icon.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SYNCEDNOTIFICATIONAPPINFO_ICON_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=454,
  serialized_end=682,
)

_SYNCEDNOTIFICATIONAPPINFO = _descriptor.Descriptor(
  name='SyncedNotificationAppInfo',
  full_name='sync_pb.SyncedNotificationAppInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_id', full_name='sync_pb.SyncedNotificationAppInfo.app_id', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='settings_display_name', full_name='sync_pb.SyncedNotificationAppInfo.settings_display_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')),
    _descriptor.FieldDescriptor(
      name='icon', full_name='sync_pb.SyncedNotificationAppInfo.icon', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')),
    _descriptor.FieldDescriptor(
      name='app_name', full_name='sync_pb.SyncedNotificationAppInfo.app_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='settings_url', full_name='sync_pb.SyncedNotificationAppInfo.settings_url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info_url', full_name='sync_pb.SyncedNotificationAppInfo.info_url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_icon', full_name='sync_pb.SyncedNotificationAppInfo.app_icon', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SYNCEDNOTIFICATIONAPPINFO_ICON, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=204,
  serialized_end=682,
)

_SYNCEDNOTIFICATIONAPPINFOSPECIFICS.fields_by_name['synced_notification_app_info'].message_type = _SYNCEDNOTIFICATIONAPPINFO
_SYNCEDNOTIFICATIONAPPINFO_ICON.fields_by_name['type'].enum_type = _SYNCEDNOTIFICATIONAPPINFO_ICON_TYPE
_SYNCEDNOTIFICATIONAPPINFO_ICON.containing_type = _SYNCEDNOTIFICATIONAPPINFO;
_SYNCEDNOTIFICATIONAPPINFO_ICON_TYPE.containing_type = _SYNCEDNOTIFICATIONAPPINFO_ICON;
_SYNCEDNOTIFICATIONAPPINFO.fields_by_name['icon'].message_type = synced_notification_render_pb2._SYNCEDNOTIFICATIONIMAGE
_SYNCEDNOTIFICATIONAPPINFO.fields_by_name['app_icon'].message_type = _SYNCEDNOTIFICATIONAPPINFO_ICON
DESCRIPTOR.message_types_by_name['SyncedNotificationAppInfoSpecifics'] = _SYNCEDNOTIFICATIONAPPINFOSPECIFICS
DESCRIPTOR.message_types_by_name['SyncedNotificationAppInfo'] = _SYNCEDNOTIFICATIONAPPINFO

class SyncedNotificationAppInfoSpecifics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SYNCEDNOTIFICATIONAPPINFOSPECIFICS

  # @@protoc_insertion_point(class_scope:sync_pb.SyncedNotificationAppInfoSpecifics)

class SyncedNotificationAppInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Icon(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SYNCEDNOTIFICATIONAPPINFO_ICON

    # @@protoc_insertion_point(class_scope:sync_pb.SyncedNotificationAppInfo.Icon)
  DESCRIPTOR = _SYNCEDNOTIFICATIONAPPINFO

  # @@protoc_insertion_point(class_scope:sync_pb.SyncedNotificationAppInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
_SYNCEDNOTIFICATIONAPPINFO.fields_by_name['settings_display_name'].has_options = True
_SYNCEDNOTIFICATIONAPPINFO.fields_by_name['settings_display_name']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')
_SYNCEDNOTIFICATIONAPPINFO.fields_by_name['icon'].has_options = True
_SYNCEDNOTIFICATIONAPPINFO.fields_by_name['icon']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\030\001')
# @@protoc_insertion_point(module_scope)
