# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: synced_notification_specifics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import synced_notification_data_pb2
import synced_notification_render_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='synced_notification_specifics.proto',
  package='sync_pb',
  serialized_pb='\n#synced_notification_specifics.proto\x12\x07sync_pb\x1a\x1esynced_notification_data.proto\x1a synced_notification_render.proto\"c\n\x1bSyncedNotificationSpecifics\x12\x44\n\x16\x63oalesced_notification\x18\x01 \x01(\x0b\x32$.sync_pb.CoalescedSyncedNotificationB\x04H\x03`\x01')




_SYNCEDNOTIFICATIONSPECIFICS = _descriptor.Descriptor(
  name='SyncedNotificationSpecifics',
  full_name='sync_pb.SyncedNotificationSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coalesced_notification', full_name='sync_pb.SyncedNotificationSpecifics.coalesced_notification', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=114,
  serialized_end=213,
)

_SYNCEDNOTIFICATIONSPECIFICS.fields_by_name['coalesced_notification'].message_type = synced_notification_data_pb2._COALESCEDSYNCEDNOTIFICATION
DESCRIPTOR.message_types_by_name['SyncedNotificationSpecifics'] = _SYNCEDNOTIFICATIONSPECIFICS

class SyncedNotificationSpecifics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SYNCEDNOTIFICATIONSPECIFICS

  # @@protoc_insertion_point(class_scope:sync_pb.SyncedNotificationSpecifics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
# @@protoc_insertion_point(module_scope)
