# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typed_url_specifics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='typed_url_specifics.proto',
  package='sync_pb',
  serialized_pb='\n\x19typed_url_specifics.proto\x12\x07sync_pb\"r\n\x11TypedUrlSpecifics\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06hidden\x18\x04 \x01(\x08\x12\x12\n\x06visits\x18\x07 \x03(\x03\x42\x02\x10\x01\x12\x1d\n\x11visit_transitions\x18\x08 \x03(\x05\x42\x02\x10\x01\x42\x04H\x03`\x01')




_TYPEDURLSPECIFICS = _descriptor.Descriptor(
  name='TypedUrlSpecifics',
  full_name='sync_pb.TypedUrlSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='sync_pb.TypedUrlSpecifics.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='sync_pb.TypedUrlSpecifics.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hidden', full_name='sync_pb.TypedUrlSpecifics.hidden', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visits', full_name='sync_pb.TypedUrlSpecifics.visits', index=3,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='visit_transitions', full_name='sync_pb.TypedUrlSpecifics.visit_transitions', index=4,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['TypedUrlSpecifics'] = _TYPEDURLSPECIFICS

class TypedUrlSpecifics(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TYPEDURLSPECIFICS

  # @@protoc_insertion_point(class_scope:sync_pb.TypedUrlSpecifics)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
_TYPEDURLSPECIFICS.fields_by_name['visits'].has_options = True
_TYPEDURLSPECIFICS.fields_by_name['visits']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_TYPEDURLSPECIFICS.fields_by_name['visit_transitions'].has_options = True
_TYPEDURLSPECIFICS.fields_by_name['visit_transitions']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
