# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unique_position.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unique_position.proto',
  package='sync_pb',
  serialized_pb='\n\x15unique_position.proto\x12\x07sync_pb\"t\n\x0eUniquePosition\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\x18\n\x10\x63ompressed_value\x18\x02 \x01(\x0c\x12\x1b\n\x13uncompressed_length\x18\x03 \x01(\x04\x12\x1c\n\x14\x63ustom_compressed_v1\x18\x04 \x01(\x0c\x42\x04H\x03`\x01')




_UNIQUEPOSITION = _descriptor.Descriptor(
  name='UniquePosition',
  full_name='sync_pb.UniquePosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='sync_pb.UniquePosition.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compressed_value', full_name='sync_pb.UniquePosition.compressed_value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uncompressed_length', full_name='sync_pb.UniquePosition.uncompressed_length', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_compressed_v1', full_name='sync_pb.UniquePosition.custom_compressed_v1', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['UniquePosition'] = _UNIQUEPOSITION

class UniquePosition(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNIQUEPOSITION

  # @@protoc_insertion_point(class_scope:sync_pb.UniquePosition)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003`\001')
# @@protoc_insertion_point(module_scope)
